version: '3'

# Test for Docker cloud/hub automation.
# This file will be called from docker hub when pushed.

services:
  sut:
    build: .
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

    command: /healthcheck.sh
