version: '3'

# Test for Docker cloud/hub automation.
# This file will be called from docker hub when pushed.

services:
  sut:
    build: .
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./Tests/run_test.sh:/run_test.sh
      - ./Tests/unsecure_dhparam.pem:/etc/nginx/dhparam/dhparam.pem
    depends_on:
      - whoami
    entrypoint:
      - /run_test.sh

  # Simple container that waits on 8000 port
  whoami:
    container_name: whoami
    image: jwilder/whoami
